version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this for better security
    depends_on:
      - prometheus
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  monitoring:
    driver: bridge
